// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu8PnJCVci8N93XdHtgIAvppDkFKIJkzI',
    appId: '1:7737962751:web:b79e33dbcb932608641cca',
    messagingSenderId: '7737962751',
    projectId: 'ecom-demo-13afe',
    authDomain: 'ecom-demo-13afe.firebaseapp.com',
    storageBucket: 'ecom-demo-13afe.appspot.com',
    measurementId: 'G-RZELCB94NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByABPMimVeJ3dwkvgpi2E0aff8m3_cXHU',
    appId: '1:7737962751:android:17f5b5597ab954d2641cca',
    messagingSenderId: '7737962751',
    projectId: 'ecom-demo-13afe',
    storageBucket: 'ecom-demo-13afe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB27UlA0h2meohbjK1xTNMWmJSxw1xtIho',
    appId: '1:7737962751:ios:657d8edb759bbf91641cca',
    messagingSenderId: '7737962751',
    projectId: 'ecom-demo-13afe',
    storageBucket: 'ecom-demo-13afe.appspot.com',
    iosBundleId: 'com.demo.ecom.taskEcomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB27UlA0h2meohbjK1xTNMWmJSxw1xtIho',
    appId: '1:7737962751:ios:657d8edb759bbf91641cca',
    messagingSenderId: '7737962751',
    projectId: 'ecom-demo-13afe',
    storageBucket: 'ecom-demo-13afe.appspot.com',
    iosBundleId: 'com.demo.ecom.taskEcomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu8PnJCVci8N93XdHtgIAvppDkFKIJkzI',
    appId: '1:7737962751:web:77069640f8c1c7bc641cca',
    messagingSenderId: '7737962751',
    projectId: 'ecom-demo-13afe',
    authDomain: 'ecom-demo-13afe.firebaseapp.com',
    storageBucket: 'ecom-demo-13afe.appspot.com',
    measurementId: 'G-BMCDSWR48F',
  );
}
